export const cleanGeneratedHtml = (html: string): string => {
  let cleaned = html;
  
  // Удаляем markdown блоки в начале и конце
  cleaned = cleaned.replace(/^```(?:html|json|markdown|)?\s*/gi, '');
  cleaned = cleaned.replace(/\s*```$/gi, '');
  
  // Удаляем возможные пояснения в начале
  cleaned = cleaned.replace(
    /^(?:\s*(?:Вот|Создал|Написал|Готово|Статья|Код|HTML|Вот статья|Результат|Генерация|Сгенерировано)[:\s\-]*\n?)+/gi, 
    ''
  );
  
  // Удаляем подписи AI в конце
  cleaned = cleaned.replace(
    /(?:\n\s*)?(?:Создано с помощью|Generated by|Автор|Это статья создана|AI помощник|Искусственный интеллект).*$/gi, 
    ''
  );

  // Удаляем лишние пробелы и переносы
  cleaned = cleaned.trim();
  
  // Ищем начало первого HTML-тега
  const htmlStartMatch = cleaned.match(/<[^>]+>/);
  if (htmlStartMatch) {
    const startIndex = cleaned.indexOf(htmlStartMatch[0]);
    if (startIndex > 0) {
      // Если перед первым тегом есть текст, удаляем его
      cleaned = cleaned.substring(startIndex);
    }
  }
  
  // Проверяем, что у нас есть валидный HTML
  if (!cleaned.match(/<[^>]+>/)) {
    // Если нет HTML-тегов, добавляем параграф
    cleaned = `<p>${cleaned}</p>`;
  }
  
  // Удаляем пустые строки в начале и конце после всех преобразований
  cleaned = cleaned.trim();
  
  return cleaned;
};