import { Brain, FileText, FolderTree, Home, MessageSquare, Plus, Tags } from "lucide-react";

export const menuItems = [
  {
    id: "cms-home",
    title: "CMS",
    description: "Главная страница управления контентом",
    icon: <Home className="w-6 h-6" />,
    color: "from-gray-500 to-gray-600",
    hoverColor: "hover:from-gray-600 hover:to-gray-700",
    shadow: "shadow-lg shadow-gray-500/20",
    path: "/administrator/cms",
  },
  {
    id: "new-article",
    title: "Новая статья",
    description: "Создать статью в редакторе",
    icon: <Plus className="w-6 h-6" />,
    color: "from-blue-500 to-blue-600",
    hoverColor: "hover:from-blue-600 hover:to-blue-700",
    shadow: "shadow-lg shadow-blue-500/20",
    path: "/administrator/cms/articles/editor",
  },
  {
    id: "all-articles",
    title: "Все статьи",
    description: "Просмотр и управление статьями",
    icon: <FileText className="w-6 h-6" />,
    color: "from-indigo-500 to-indigo-600",
    hoverColor: "hover:from-indigo-600 hover:to-indigo-700",
    shadow: "shadow-lg shadow-indigo-500/20",
    path: "/administrator/cms/articles/articlesManagement",
  },
  {
    id: "categories",
    title: "Категории",
    description: "Управление категориями блога",
    icon: <FolderTree className="w-6 h-6" />,
    color: "from-green-500 to-green-600",
    hoverColor: "hover:from-green-600 hover:to-green-700",
    shadow: "shadow-lg shadow-green-500/20",
    path: "/administrator/cms/categories",
  },
  {
    id: "semantic-core",
    title: "Семантическое ядро",
    description: "Ключевые слова и SEO",
    icon: <Tags className="w-6 h-6" />,
    color: "from-purple-500 to-purple-600",
    hoverColor: "hover:from-purple-600 hover:to-purple-700",
    shadow: "shadow-lg shadow-purple-500/20",
    path: "/administrator/cms/semantic-core",
  },
  {
    id: "auto-generate",
    title: "Автогенерация",
    description: "Автогенерация статей",
    icon: <Brain className="w-6 h-6" />,
    color: "from-orange-500 to-orange-600",
    hoverColor: "hover:from-orange-600 hover:to-orange-700",
    shadow: "shadow-lg shadow-orange-500/20",
    path: "/administrator/cms/auto-generate",
  },
  {
    id: "comments",
    title: "Комментарии",
    description: "Управление комментариями",
    icon: <MessageSquare className="w-6 h-6" />,
    color: "from-gray-500 to-gray-600",
    hoverColor: "hover:from-gray-600 hover:to-gray-700",
    shadow: "shadow-lg shadow-gray-500/20",
    path: "/administrator/cms/comments",
  },
];
